/* Drop foreinkeys first */


/* Drop existing tables*/
DROP TABLE IF EXISTS MITARBEITER;
DROP TABLE IF EXISTS PROJEKT;
DROP TABLE IF EXISTS ABTEILUNG;
DROP TABLE IF EXISTS GEHALTSGRUPPE;
DROP TABLE IF EXISTS FERIEN;

CREATE TABLE MITARBEITER(
PID INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Vorname VARCHAR(50) NOT NULL,
Eintrittsdatum DATE NOT NULL, 
Bonus INT DEFAULT(0),
Abteilung,
Gehaltsgruppe,
StellvertreterID int 
CONSTRAINT PID_LENGTH CHECK (PID BETWEEN 1000 AND 9999)
);

CREATE TABLE GEHALTSGRUPPE(
GID INT PRIMARY KEY,
GEH INT NOT NULL,
CONSTRAINT ID_LENGTH CHECK (GID BETWEEN 10 AND 99)
);

CREATE TABLE PROJEKT(
PID INT PRIMARY KEY,
Projektleiter,
Bezeichnung VARCHAR(100),
Startdatum DATE,
Enddatum DATE,
ParentProjekt
);

CREATE TABLE ABTEILUNG(
AID INT PRIMARY KEY
Bezeichnung
Kurzbezeichnung
Abteilungsleiter
);

CREATE TABLE FERIEN(
FID
Erster_Urlaubstag
Letzter_Urlaubstag
Mitarbeiter
Status
Genutzte_Ferientage
Beantragt_am
Genehmigung
Genehmigung_am
Storniert_am
);