/* Alter existing tables */
ALTER TABLE
    MITARBEITER
ADD
    CONSTRAINT FK_Gehaltsgruppe FOREIGN KEY (GehaltsgruppeID) REFERENCES GEHALTSGRUPPE(GID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    MITARBEITER
ADD
    CONSTRAINT FK_Abteilung FOREIGN KEY (AbteilungsID) REFERENCES ABTEILUNG(AID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    MITARBEITER
ADD
    CONSTRAINT FK_Stellvertreter FOREIGN KEY (StellvertreterID) REFERENCES MITARBEITER(PID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    MITARBEITER
ADD
    CONSTRAINT FK_Bonus FOREIGN KEY (BonusID) REFERENCES BONUS(BID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PROJEKT
ADD
    CONSTRAINT FK_ParentProjekt FOREIGN KEY (ParentProjektID) REFERENCES PROJEKT(ProjektID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PROJEKT
ADD
    CONSTRAINT FK_Projektleiter FOREIGN KEY (ProjektleiterID) REFERENCES MITARBEITER(PID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PROJEKT_MITARBEITER
ADD
    CONSTRAINT FK_Mitarbeiter_Projekt_Mitarbeiter FOREIGN KEY (MitarbeiterID) REFERENCES MITARBEITER(PID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PROJEKT_MITARBEITER
ADD
    CONSTRAINT FK_Projekt FOREIGN KEY (ProjektID) REFERENCES PROJEKT(ProjektID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    ABTEILUNGSLEITER
ADD
    CONSTRAINT FK_Mitarbeiter_Abteilungsleiter FOREIGN KEY (MitarbeiterID) REFERENCES MITARBEITER(PID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    ABTEILUNGSLEITER
ADD
    CONSTRAINT FK_Abteilung_Abteilungsleiter FOREIGN KEY (AbteilungsID) REFERENCES ABTEILUNG(AID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    FERIEN
ADD
    CONSTRAINT FK_Mitarbeiter_Ferien FOREIGN KEY (MitarbeiterID) REFERENCES MITARBEITER(PID) ON DELETE NO ACTION ON UPDATE NO ACTION;