/* Drop foreinkeys first */


/* Drop existing tables*/
DROP TABLE IF EXISTS MITARBEITER;
DROP TABLE IF EXISTS PROJEKT;
DROP TABLE IF EXISTS ABTEILUNG;
DROP TABLE IF EXISTS GEHALTSGRUPPE;
DROP TABLE IF EXISTS FERIEN;

CREATE TABLE MITARBEITER(
PID int PRIMARY KEY,
Name VARCHAR(50),
Vorname VARCHAR(50),
Eintrittsdatum, 
Abteilung
Gehaltsgruppe,
Stellvertreter
CONSTRAINT PID_LENGTH CHECK (PID BETWEEN 1 AND 9999)
);


CREATE TABLE PROJEKT(

);

CREATE TABLE GEHALTSGRUPPE(

);

CREATE TABLE ABTEILUNG(

);

CREATE TABLE FERIEN(

);