/* Drop existing Views */
DROP VIEW IF EXISTS GEHALTSGRUPPE_20_UND_GEHALT;

DROP VIEW IF EXISTS MITARBEITER_MEISTE_PROJEKTE;

DROP VIEW IF EXISTS MIN_MAX_GEHALT_ABTEILUNGSLEITER;

DROP VIEW IF EXISTS MITARBEITER_10_JAHRE_ANGESTELLT;

DROP VIEW IF EXISTS MITARBEITER_IN_FERIEN;

/* Drop existing tables*/
DROP TABLE IF EXISTS ABTEILUNGSLEITER;

DROP TABLE IF EXISTS PROJEKT_MITARBEITER;

DROP TABLE IF EXISTS FERIEN;

DROP TABLE IF EXISTS PROJEKT;

DROP TABLE IF EXISTS MITARBEITER;

DROP TABLE IF EXISTS BONUS;

DROP TABLE IF EXISTS ABTEILUNG;

DROP TABLE IF EXISTS GEHALTSGRUPPE;