/* Drop existing tables*/
DROP TABLE IF EXISTS ABTEILUNGSLEITER;

DROP TABLE IF EXISTS PROJEKT_MITARBEITER;

DROP TABLE IF EXISTS FERIEN;

DROP TABLE IF EXISTS PROJEKT;

DROP TABLE IF EXISTS MITARBEITER;

DROP TABLE IF EXISTS BONUS;

DROP TABLE IF EXISTS ABTEILUNG;

DROP TABLE IF EXISTS GEHALTSGRUPPE;